### PR TITLE
Replaced Multiplication and Division by bit shift operation

### PR DESCRIPTION
**Pull request by GYuvanShankar**

### CODE REVIEW

**Comment by Lastique** [comment]
On any remotely decent compiler there'll be no performance difference. Also compile-time constant expressions don't affect runtime performance.

**Comment by GYuvanShankar** [comment]
Oh alright, thanks. Will there be any difference, if the said operation is in a loop? Or if the divisor is a higher power of two?

**Comment by Lastique** [comment]
Any compiler will replace the division by a power of two with a shift. Plus maybe a check whether the dividend is negative, if the compiler can't deduce that this is never a case. If dividend is never negative, it would make sense to make it `unsigned`, which would reliably eliminate the check.

For signed integers, it is generally preferred to use arithmetic operators rather than bitwise because of this difference wrt. negative values and because prior to C++20 signed integers could have non-two's-complement representation.

**Comment by GYuvanShankar** [comment]
Thanks. Will close this PR

**Pull request closed without merging**
